name: exercise2

on: [push]

env:
        ARTIFACT_NAME: myartifact

jobs:

        job1:
                runs-on: ubuntu-latest
                steps:   
                        - name: Checkout
                          use: actions/checkout@v2

                        - name: Upload Artifact
                          use: actions/upload-artifact@v2
                          with:
                                  name: ${{ env.ARTIFACT_NAME }}
                                  path: .


